services:
  app:
    build:
      context: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/dev-tech-blog
      DB_USER: dev-tech-blog
      DB_PASSWORD: dev-tech-blog
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/dev-tech-blog:z
    depends_on:
      db:
        condition: service_healthy #faz com que o app só tente subir depois que o banco estiver 100% pronto.
    networks:
      - dev-tech-blog-net
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: dev-tech-blog
      POSTGRES_PASSWORD: dev-tech-blog
      POSTGRES_DB: dev-tech-blog
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "5432:5432"
    networks:
      - dev-tech-blog-net
    healthcheck: #verifica a cada 5 segundos se o Postgres está aceitando conexões.
      test: [ "CMD-SHELL", "pg_isready -U dev-tech-blog" ]
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  dev-tech-blog-net:
    name: dev-tech-blog-net
    external: false
volumes:
  db: