spring:
    application:
        name: dev-tech-blog
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate